### ISSUE TITLE
`undefined local variable or method 'testrail'`

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE-QA/testing-site-onlyoffice#273]
Please, take a look ASAP:

1. Simplify hourly_check to this variant: (removed all tests except first one and make it hard-fail)
```
# frozen_string_literal: true

require 'spec_helper'

describe 'SiteHourlyCheck' do
  test_run = "Site Hourly Checks version: #{TestingSiteOnlyoffice::SiteVersionHelper.full_site_version}, time: #{Time.new}, region: #{config.region}"
  test_manager = TestingSiteOnlyoffice::TestManager.new(suite_name: File.basename(__FILE__), plan_name: test_run, plan_name_testrail: test_run, product_name: 'Site Hourly Check')
  run_name = nil

  after do |example|
    test_manager&.add_result(example, @test)
    @test&.webdriver&.quit
    @test&.webdriver&.quit
    WebDriver.clean_up

    unless OnlyofficeFileHelper::RubyHelper.debug?
      fail = example.exception
      if fail && run_name == example.description && !run_name.include?('[Info]') && !TestingSiteOnlyoffice::TeamlabFailNotifier.should_be_ignored?(example)
        message_body = "#{test_run}\n#{run_name}\n#{fail}\n#{testrail&.run&.url}"
        message_report = { subject: '[Error] Site Hourly', body: message_body }
        they_want_to_know = %w[nct.tester@yandex.ru test.teamlab@yandex.ru shockwavenn@gmail.com
                               denis.spitsyn.nct@gmail.com]
        TestingSiteOnlyoffice::TeamlabFailNotifier.send(message_body)
        Gmail_helper.new('onlyoffice.daily.report@gmail.com', 'onlyoffice.daily.report1').send_mail(they_want_to_know,
                                                                                                    message_report[:subject], message_report[:body])
      end
      run_name = example.description
    end
  end

  describe 'Site onlyoffice.com' do
    before do
      @site_home_page, @test = TestingSiteOnlyoffice::SiteHelper.new.open_page_teamlab_office(config)
    end

    it '[Site] Check exists languages' do
      expect(@site_home_page.get_all_language_from_site.sort).to eq('test-failure_ignore')
    end
  end
end

```

2. Run it

3. Get:
```
0) SiteHourlyCheck Site onlyoffice.com [Site] Check exists languages
     Got 1 failure and 1 other error:

     0.1) Failure/Error: expect(@site_home_page.get_all_language_from_site.sort).to eq('test-failure_ignore')

            expected: "test-failure_ignore"
                 got: ["cs-CZ", "de-DE", "en-GB", "en-US", "es-ES", "fr-FR", "it-IT", "ja-JP", "nl-NL", "pt-BR", "ru-RU", "zh-CN"]

            (compared using ==)
          # ./spec/site_hourly_check_spec.rb:37:in `block (3 levels) in <top (required)>'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

     0.2) Failure/Error: message_body = "#{test_run}\n#{run_name}\n#{fail}\n#{testrail&.run&.url}"

          NameError:
            undefined local variable or method `testrail' for #<RSpec::ExampleGroups::SiteHourlyCheck::SiteOnlyofficeCom:0x00005624d01413d8>
          # ./spec/site_hourly_check_spec.rb:19:in `block (2 levels) in <top (required)>'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
          # /home/lobashov/.rvm/gems/ruby-2.7.3/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
```
          
          
I think broken at https://github.com/ONLYOFFICE-QA/testing-site-onlyoffice/pull/206/files#diff-34c3cdce7e94e9330cadd6949fbb74c6cee5ebaf6779591dc909ccfc5cf2b525R5
